services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8888:8000"
    restart: on-failure
    command: >
      sh -c "python backend/manage.py wait_db && python backend/manage.py runserver 0.0.0.0:8000"
  
  

  db:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./mysql_db:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: on-failure


  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./backend/static:/usr/share/nginx/doc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure



