# Generated by Django 5.1.3 on 2024-11-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Українська гривня'), ('EUR', 'Євро'), ('USD', 'Долар США')], default='EUR', max_length=5),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('pending', 'На розгляді')], default='active', max_length=25),
        ),
    ]
