# Generated by Django 5.1.3 on 2024-12-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_currency_alter_carmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='status',
        ),
    ]
